services:
  - type: web
    name: football-matches
    env: docker
    plan: starter
    buildCommand: "docker build -t football-matches ."
    startCommand: "docker run -p 80:80 football-matches"
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FOOTBALL_API_KEY
        sync: false